package com.geekonsites.backend.enums;

public enum BookingStatus {
    PENDING,
    PAYMENT_COMPLETED,
    ASSIGNMENT_PENDING,

    TECHNICIAN_ASSIGNED,
    TECHNICIAN_ACCEPTED,
    TECHNICIAN_REJECTED,
    TECHNICIAN_ON_THE_WAY,
    TECHNICIAN_ARRIVED,

    SERVICE_STARTED,
    REMOTE_SESSION_STARTED,
    SERVICE_COMPLETED,

    INVOICE_GENERATED,
    REMAINING_PAYMENT_PENDING,
    FULLY_PAID,
    BOOKING_CLOSED,

    CANCELLED
}