-- =============================================================================
-- PHASE 8 — V1 baseline schema
-- =============================================================================
-- This is the canonical, PostgreSQL-only baseline of the GeekOnSites schema as it
-- exists after Phases 0-7. It was generated from the JPA entity model with
-- Hibernate's PostgreSQLDialect (CamelCaseToUnderscores physical naming) and then
-- made idempotent, so it is safe on BOTH:
--   * a fresh, empty database  -> creates the whole schema; and
--   * a pre-Flyway existing DB -> every statement is a no-op (the objects already
--                                 exist), and Flyway records the version.
--
-- Do NOT edit the meaning of this file after it has been applied anywhere: add a
-- new V<n> migration instead.
--
-- Every table uses `CREATE TABLE IF NOT EXISTS`; every index uses
-- `CREATE INDEX IF NOT EXISTS`; the two FK constraints that Hibernate itself
-- declares (token -> users) are guarded by a catalog check.
-- =============================================================================

create table if not exists agents (
    id bigint generated by default as identity,
    city varchar(255),
    country varchar(255),
    email varchar(255) unique,
    name varchar(255),
    phone varchar(255),
    status varchar(255),
    primary key (id)
);

create table if not exists users (
    country varchar(2),
    id bigint generated by default as identity,
    email varchar(255) not null unique,
    full_name varchar(255),
    password varchar(255),
    phone varchar(255),
    role varchar(255) check (role in ('CUSTOMER','TECHNICIAN','AGENT','ADMIN')),
    primary key (id)
);

create table if not exists technicians (
    experience_years integer,
    rating float(53),
    company_email_assigned_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    onboarding_email_sent_at timestamp(6) with time zone,
    password_setup_completed_at timestamp(6) with time zone,
    address_history varchar(255),
    address_proof_name varchar(255),
    availability_status varchar(255),
    citizenship_status varchar(255),
    city varchar(255),
    company_email varchar(255) unique,
    country varchar(255),
    driving_license_name varchar(255),
    email varchar(255) unique,
    employment_type varchar(255),
    identity_document_name varchar(255),
    identity_document_type varchar(255),
    name varchar(255),
    onboarding_status varchar(255) check (onboarding_status in ('NOT_STARTED','SETUP_PENDING','EMAIL_SENT','EMAIL_FAILED','PASSWORD_SET')),
    personal_email varchar(255),
    phone varchar(255),
    public_liability_name varchar(255),
    service_mode varchar(255),
    specialization varchar(255),
    vehicle_insurance_name varchar(255),
    verification_status varchar(255),
    work_authorization_document_name varchar(255),
    work_authorization_expiry varchar(255),
    work_authorization_type varchar(255),
    address_proof_data TEXT,
    driving_license_data TEXT,
    identity_document_data TEXT,
    live_photo_data TEXT,
    public_liability_data TEXT,
    vehicle_insurance_data TEXT,
    work_authorization_document_data TEXT,
    primary key (id)
);

create table if not exists password_reset_tokens (
    used boolean not null,
    created_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    user_id bigint not null,
    token_hash varchar(64) not null unique,
    primary key (id)
);

create table if not exists technician_onboarding_tokens (
    used boolean not null,
    created_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    technician_id bigint not null,
    user_id bigint not null,
    token_hash varchar(64) not null unique,
    primary key (id)
);

create table if not exists bookings (
    addons_amount float(53),
    advance_amount float(53),
    base_amount float(53),
    booking_closed boolean,
    booking_date date,
    customer_latitude float(53),
    customer_longitude float(53),
    customer_rating integer,
    eta_minutes integer,
    invoice_generated boolean,
    paid_amount float(53),
    platform_fee float(53),
    protection_amount float(53),
    remaining_amount float(53),
    remaining_distance_km float(53),
    remote_session_required boolean,
    technician_arrived boolean,
    technician_heading float(53),
    technician_latitude float(53),
    technician_longitude float(53),
    technician_speed float(53),
    total_amount float(53),
    tracking_enabled boolean,
    uk_early_service_consent boolean default false not null,
    agent_id bigint,
    booking_closed_at timestamp(6),
    created_at timestamp(6),
    customer_id bigint,
    estimated_arrival_time timestamp(6),
    id bigint generated by default as identity,
    invoice_generated_at timestamp(6),
    last_location_update timestamp(6),
    rated_at timestamp(6),
    remote_session_ended_at timestamp(6),
    remote_session_scheduled_end timestamp(6),
    remote_session_scheduled_start timestamp(6),
    remote_session_started_at timestamp(6),
    service_completed_at timestamp(6),
    service_id bigint,
    service_started_at timestamp(6),
    technician_accepted_at timestamp(6),
    technician_id bigint,
    technician_on_the_way_at timestamp(6),
    technician_rejected_at timestamp(6),
    uk_early_service_consent_at timestamp(6),
    updated_at timestamp(6),
    selected_addons varchar(2000),
    address varchar(255),
    agent_name varchar(255),
    booking_status varchar(255) check (booking_status in ('PENDING','PAYMENT_COMPLETED','ASSIGNMENT_PENDING','TECHNICIAN_ASSIGNED','TECHNICIAN_ACCEPTED','TECHNICIAN_REJECTED','TECHNICIAN_ON_THE_WAY','TECHNICIAN_ARRIVED','SERVICE_STARTED','REMOTE_SESSION_STARTED','SERVICE_COMPLETED','INVOICE_GENERATED','REMAINING_PAYMENT_PENDING','FULLY_PAID','BOOKING_CLOSED','CANCELLED')),
    city varchar(255),
    country varchar(255),
    currency varchar(255),
    current_road varchar(255),
    customer_email varchar(255),
    customer_name varchar(255),
    customer_phone varchar(255),
    customer_review TEXT,
    google_calendar_event_id varchar(255),
    invoice_number varchar(255),
    issue_description TEXT,
    live_tracking_status varchar(255),
    payment_method varchar(255),
    payment_status varchar(255),
    payment_transaction_id varchar(255),
    payment_type varchar(255),
    postal_code varchar(255),
    protection_plan varchar(255),
    remote_session_link varchar(255),
    remote_session_provisioning_error TEXT,
    remote_session_status varchar(255),
    service_code_snapshot varchar(255),
    service_mode varchar(255) check (service_mode in ('REMOTE','ONSITE','HYBRID')),
    service_mode_snapshot varchar(255),
    service_name_snapshot varchar(255),
    service_type varchar(255),
    state varchar(255),
    technician_name varchar(255),
    technician_phone varchar(255),
    technician_reject_reason varchar(255),
    time_slot varchar(255),
    uk_early_service_consent_text_version varchar(255),
    primary key (id)
);

create table if not exists invoices (
    amount float(53),
    paid_amount float(53),
    booking_id bigint not null unique,
    customer_id bigint,
    id bigint generated by default as identity,
    issued_at timestamp(6),
    technician_id bigint,
    currency varchar(255),
    customer_name varchar(255),
    invoice_number varchar(255),
    payment_method varchar(255),
    payment_status varchar(255),
    payment_transaction_id varchar(255),
    service_type varchar(255),
    technician_name varchar(255),
    primary key (id)
);

create table if not exists ratings (
    rating integer,
    booking_id bigint not null unique,
    customer_id bigint,
    id bigint generated by default as identity,
    technician_id bigint,
    review varchar(255),
    primary key (id)
);

create table if not exists notifications (
    is_read boolean,
    admin_id bigint,
    agent_id bigint,
    booking_id bigint,
    created_at timestamp(6),
    customer_id bigint,
    id bigint generated by default as identity,
    technician_id bigint,
    action_url varchar(255),
    idempotency_key varchar(255) unique,
    message varchar(255),
    recipient_role varchar(255),
    title varchar(255),
    type varchar(255),
    primary key (id)
);

create table if not exists payment_transactions (
    currency varchar(3) not null,
    excess boolean default false not null,
    amount_minor bigint not null,
    booking_id bigint not null,
    checkout_expires_at timestamp(6),
    completed_at timestamp(6),
    created_at timestamp(6) not null,
    customer_id bigint,
    id bigint generated by default as identity,
    reversal_attempted_at timestamp(6),
    updated_at timestamp(6) not null,
    payment_type varchar(20) not null check (payment_type in ('FULL','ADVANCE','REMAINING')),
    provider varchar(20) not null check (provider in ('STRIPE')),
    reversal_status varchar(20) check (reversal_status in ('NOT_REQUIRED','PENDING','SUCCEEDED','FAILED')),
    status varchar(20) not null check (status in ('INITIATED','CHECKOUT_CREATED','SUCCEEDED','FAILED','CANCELLED','EXPIRED')),
    reversal_error varchar(500),
    checkout_url varchar(1024),
    checkout_session_id varchar(255) unique,
    payment_intent_id varchar(255),
    reversal_refund_id varchar(255),
    primary key (id)
);

create table if not exists payment_refunds (
    currency varchar(3) not null,
    amount_minor bigint not null,
    completed_at timestamp(6),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    payment_transaction_id bigint not null,
    refund_request_id bigint not null,
    updated_at timestamp(6) not null,
    status varchar(20) not null check (status in ('PENDING','SUCCEEDED','FAILED','CANCELLED')),
    idempotency_key varchar(160) not null unique,
    payment_intent_id varchar(255),
    provider_refund_id varchar(255) unique,
    primary key (id)
);

create table if not exists refund_requests (
    approved_refund_amount numeric(12,2),
    country varchar(2) not null,
    currency varchar(3) not null,
    original_payment_amount numeric(12,2) not null,
    requested_refund_amount numeric(12,2) not null,
    suggested_maximum_refund_amount numeric(12,2) not null,
    booking_id bigint not null,
    created_at timestamp(6),
    customer_id bigint not null,
    id bigint generated by default as identity,
    processed_at timestamp(6),
    requested_at timestamp(6) not null,
    reviewed_at timestamp(6),
    reviewed_by_admin_id bigint,
    updated_at timestamp(6),
    refund_status varchar(32) not null check (refund_status in ('REQUESTED','UNDER_REVIEW','APPROVED','REJECTED','PROCESSING','REFUNDED','PARTIALLY_REFUNDED','FAILED','CANCELLED')),
    refund_reason varchar(120) not null,
    admin_note TEXT,
    customer_message TEXT,
    failure_reason TEXT,
    rule_context TEXT not null,
    stripe_payment_intent_id varchar(255),
    stripe_refund_id varchar(255),
    primary key (id)
);

create table if not exists remote_chat_messages (
    booking_id bigint not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    read_at timestamp(6),
    sender_user_id bigint not null,
    sender_role varchar(20) not null,
    message varchar(2000) not null,
    primary key (id)
);

create table if not exists service_addons (
    active boolean default true not null,
    sort_order integer,
    created_at timestamp(6) not null,
    gbp_amount_minor bigint not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    usd_amount_minor bigint not null,
    code varchar(120) not null unique,
    name varchar(200) not null,
    primary key (id)
);

create table if not exists services (
    active boolean default true not null,
    sort_order integer,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    service_mode varchar(20) not null check (service_mode in ('REMOTE','ONSITE','HYBRID')),
    code varchar(120) not null unique,
    name varchar(200) not null,
    description varchar(1000),
    primary key (id)
);

create table if not exists service_prices (
    currency varchar(3) not null check (currency in ('USD','GBP')),
    amount_minor bigint not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    service_id bigint not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint uq_service_price_currency unique (service_id, currency)
);

create table if not exists push_device_tokens (
    active boolean not null,
    created_at timestamp(6) not null,
    customer_id bigint not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    platform varchar(20) not null,
    recipient_role varchar(20),
    token varchar(2048) not null,
    primary key (id),
    unique (token)
);

create table if not exists contact_messages (
    country varchar(2) not null,
    created_at timestamp(6) not null,
    customer_id bigint,
    id bigint generated by default as identity,
    resolved_at timestamp(6),
    updated_at timestamp(6) not null,
    email varchar(255) not null,
    full_name varchar(255) not null,
    message TEXT not null,
    phone varchar(255) not null,
    status varchar(255) not null,
    subject varchar(255) not null,
    primary key (id)
);

create table if not exists crm_notes (
    agent_id bigint,
    created_at timestamp(6) not null,
    customer_id bigint not null,
    id bigint generated by default as identity,
    author_name varchar(255) not null,
    author_role varchar(255) not null,
    note_text TEXT not null,
    primary key (id)
);

create table if not exists crm_follow_ups (
    agent_id bigint,
    completed_at timestamp(6),
    created_at timestamp(6) not null,
    customer_id bigint not null,
    follow_up_at timestamp(6) not null,
    id bigint generated by default as identity,
    internal_note TEXT,
    owner_name varchar(255) not null,
    owner_role varchar(255) not null,
    reason varchar(255) not null,
    status varchar(255) not null check (status in ('PENDING','COMPLETED','CANCELLED')),
    primary key (id)
);

-- -----------------------------------------------------------------------------
-- Indexes declared by the entity model (Hibernate @Index / @Table).
-- -----------------------------------------------------------------------------
create index if not exists idx_crm_followup_customer on crm_follow_ups (customer_id);
create index if not exists idx_crm_followup_due on crm_follow_ups (status, follow_up_at);
create index if not exists idx_crm_notes_customer on crm_notes (customer_id);
create index if not exists idx_payment_refund_request on payment_refunds (refund_request_id);
create index if not exists idx_payment_refund_tx on payment_refunds (payment_transaction_id);
create index if not exists idx_payment_tx_booking on payment_transactions (booking_id);
create index if not exists idx_payment_tx_status on payment_transactions (status);
create index if not exists idx_refund_booking on refund_requests (booking_id);
create index if not exists idx_refund_customer on refund_requests (customer_id);
create index if not exists idx_refund_status on refund_requests (refund_status);
create index if not exists idx_remote_chat_booking_created on remote_chat_messages (booking_id, created_at);
create index if not exists idx_service_price_service on service_prices (service_id);
create index if not exists idx_technician_onboarding_technician on technician_onboarding_tokens (technician_id);

-- -----------------------------------------------------------------------------
-- FK constraints declared by the entity model (token -> users), named exactly as
-- PostgreSQL would name them so this block is idempotent on pre-Flyway databases.
-- -----------------------------------------------------------------------------
do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fkk3ndxg5xp6v7wd4gjyusp15gq') then
        alter table if exists password_reset_tokens
            add constraint fkk3ndxg5xp6v7wd4gjyusp15gq foreign key (user_id) references users;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'fk1qrairkr18kce1jyjc2yrdvs8') then
        alter table if exists technician_onboarding_tokens
            add constraint fk1qrairkr18kce1jyjc2yrdvs8 foreign key (user_id) references users;
    end if;
end $$;
